### ISSUE TITLE
If sender doesn't not have sufficient balance for gas we send back wrong RPC response

### ISSUE THREAD

**Issue by tomtomcrypto** [telosnetwork/telos-evm-rpc#64]
We send back

```
ProviderError: eosio_assert_message assertion failure at /v1/chain/send_transaction
    at HttpProvider.request (/home/tom/pancake-v3-contracts/node_modules/hardhat/src/internal/core/providers/http.ts:88:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at EthersProviderWrapper.send (/home/tom/pancake-v3-contracts/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /home/tom/.nvm/versions/node/v18.18.0/bin/node
Arguments: /home/tom/.cache/node/corepack/yarn/1.22.21/lib/cli.js run hardhat run scripts/deploy2.ts --network telosMainnet
Directory: /home/tom/pancake-v3-contracts/projects/router
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
Error: ProviderError: eosio_assert_message assertion failure at /v1/chain/send_transaction
    at HttpProvider.request (/home/tom/pancake-v3-contracts/node_modules/hardhat/src/internal/core/providers/http.ts:88:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at EthersProviderWrapper.send (/home/tom/pancake-v3-contracts/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
error Command failed with exit code 1.
error Command failed.
Exit code: 1
```

Altho the correct error message is logged in RPC.

We should use that message in the RPC response itself

**Comment by tomtomcrypto** [comment]
Will look at bit mroe but this looks solved


![Image](https://github.com/telosnetwork/telos-evm-rpc/assets/5913758/b7ff5ede-d52c-46cb-a9c3-2d2557a194cd)
